name: Create OS Package
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      file-ext:
        required: true
        type: string
      file-name:
        required: true
        type: string
      upload-url:
        required: true
        type: string

permissions:
  id-token: write
  contents: write

jobs:
  Package-Executables:
    if: contains(github.ref, 'main') || contains(github.ref, 'develop') || contains(github.ref, 'cli_package_action') 
    runs-on: ${{ inputs.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Create Essential Packages
        working-directory: cli
        run: ${{ inputs.os != 'windows-latest' && 'chmod +x ./mvnw &&' || '' }} ./mvnw package
      
      - name: Create Runtime
        working-directory: cli
        run: |
          jlink --output minimal-jvm --module-path ./target/lib --add-modules java.base,java.xml,java.sql,java.prefs,java.desktop
      
      - name: Build Artifacts
        working-directory: cli
        run: |
          jpackage --type ${{ inputs.file-ext }} -n MrBeanStoreCLI --runtime-image minimal-jvm --main-jar MrBeanStoreCLI-0.0.1-SNAPSHOT.jar -i ${{ inputs.os == 'windows-latest' && '.\target\ --win-menu --win-console' || './target' }}

      - name: Upload CLI Artifactis
        id: release_artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ inputs.upload_url }}
          asset_path: ./cli/${{ inputs.file-name }}
          asset_name: ${{ inputs.file-name }}
          asset_content_type: application/zip