name: Create OS Package
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      file-ext:
        required: true
        type: string
      file-name:
        required: true
        type: string

permissions:
  id-token: write
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  - name: Package Executable (${{ inputs.os }})
    runs-on: ${{ inputs.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Branch
          uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: pulumi-github-oidc
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Create Essential Packages
        working-directory: cli
        run: ${{ inputs.os != 'windows-latest' && 'chmod +x ./mvnw &&' || '' }} ./mvnw package
      
      - name: Create Runtime
        working-directory: cli
        run: |
          jlink --output minimal-jvm --module-path ./target/lib --add-modules java.base,java.xml,java.sql,java.prefs,java.desktop
      
      - name: Build Artifacts
        working-directory: cli
        run: |
          jpackage --type ${{ inputs.file-ext }} -n MrBeanStoreCLI --runtime-image minimal-jvm --main-jar MrBeanStoreCLI-0.0.1-SNAPSHOT.jar -i ${{ inputs.os == 'windows-latest' && '.\target\ --win-menu --win-console' || './target' }}

      - name: Get Release Upload URL File
        run: aws s3api get-object --bucket ${{ secrets.AWS_BUCKET_NAME }} --key upload_url upload_url

      - name: Env Upload URL For Unix Systems
        if: ${{ inputs.os != 'windows-latest' }}
        run: echo "UPLOAD_URL=$(head -1 ./upload_url)" >> $GITHUB_ENV

      - name: Get Release Upload URL For Windows
        if: ${{ inputs.os == 'windows-latest' }}
        shell: pwsh
        run: |
          $url = Get-Content -Path ".\upload_url" -TotalCount 1
          Add-Content -Path $env:GITHUB_ENV -Value "UPLOAD_URL=$url"

      - name: Upload CLI Artifactis
        id: release_artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./cli/${{ inputs.file-name }}
          asset_name: ${{ inputs.file-name }}
          asset_content_type: application/zip