name: Package Cli
on: 
  workflow_call:
    inputs:
      upload-url:
        required: true
        type: string
jobs:
    Package-Cli:
      strategy:
        matrix:
          os: [ubuntu-latest, macos-lates, windows-latest]
          include:
            - os: ubuntu-latest
              release-suffix: ubuntu
            - os: macos-latest
              release-suffix: macos
            - os: windows-latest
              release-suffix: windows

      runs-on: ${{ matrix.os }}
      steps:
        - name: Test Call
          run: echo "Hello from ${{ matrix.release-suffix }}"