- name: Set Up Server
  hosts: all
  tasks:
    - name: Link Python3
      ansible.builtin.shell: |
        rm /usr/bin/python 2> /dev/null && 
        ln -s /usr/bin/python3.9 /usr/bin/python
      become: true

    - name: Install Git
      ansible.builtin.dnf:
        name: git
        state: latest
      become: true

    - name: Install Java
      ansible.builtin.dnf:
        name:  java-21-amazon-corretto
        state: latest
      become: true

    - name: Download Server Jar
      ansible.builtin.shell: |
        cd ~ &&
        wget {{ SERVER_JAR_PATH }} &&
        java -jar ddevBean-0.0.1.jar

    - name: Print message
      ansible.builtin.debug:
        msg: Hello world