- name: My first play
  hosts: all
  tasks:
  - name: Install Git
    ansible.builtin.yun:
      name: git
      state: latest

  - name: Install Java
    ansible.builtin.yun:
      name: java-21-openjdk

  - name: Execute shell command
    ansible.builtin.shell: git clone git@github.com:Mr-Bean-Store/MrBeanStore.git
  
  - name: Print message
    ansible.builtin.debug:
      msg: Hello world