- name: Set Up Server
  hosts: all
  tasks:
    - name: Install Java
      ansible.builtin.dnf:
        name:  java-21-amazon-corretto
        state: latest
      become: true

    - name: Download Server Jar
      ansible.builtin.shell: |
        cd ~ &&
        rm -rf ./devBean-0.0.1.jar &&
        wget {{ SERVER_JAR_PATH }}
    
    - name: Kill Previous Server Instance
      ansible.builtin.shell: |
        if [[ $(lsof -t -i:8090 | wc -l) -eq 0 ]]; then echo "Nothing to kill"; else kill -TERM $(lsof -t -i:8090); fi

    - name: Start Server
      ansible.builtin.shell: |
        nohup java -jar ~/devBean-0.0.1.jar --spring.datasource.url=jdbc:postgresql://${{ DB_URL }}/${{ DB_INSTANCE_NAME }} --spring.datasource.username=${{ DB_USER }} --spring.datasource.password=${{ DB_PASSWORD }} &
      become: true

    - name: Print message
      ansible.builtin.debug:
        msg: Hello world