name: pull_request_pulumi_dev
on:
  push:
    branches:
      - feature/pulumi_aws_connection
permissions:
  id-token: write
  contents: read
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: 3.10.1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: pulumi-github-oidc
      - run: pip install -r requirements.txt
        working-directory: infrastructure
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
          work-dir: infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
