name: pull_request_pulumi_dev
on:
  push:
    branches:
      - "feature/pulumi_*"
permissions:
  id-token: write
  contents: read
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Pulumi
        secrets: inherit
        uses: ./.github/workflows/pulumi_run_command
        with:
          command: preview

