name: Package Artifacts
on: 
  push:
    tags:
      - "*"
  
jobs:
    Package-Artifacts:
      strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
          include:
            - os: ubuntu-latest
              release-suffix: ubuntu
            - os: macos-latest
              release-suffix: macos
            - os: windows-latest
              release-suffix: windows

      runs-on: ${{ matrix.os }}
      steps:
        - name: Test Call
          run: echo "Hello from ${{ matrix.os }}"