name: Package Artifacts
on: 
  push:
    tags:
      - "*"
    branches:
      - feature/cli_package_action

permissions:
  id-token: write
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
    Package-Artifacts:
      runs-on: ubuntu-latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      steps:
        - name: Ubuntu
          uses: ./.github/workflows/create-os-package
          with:
            os: ubuntu-latest
            file-ext: deb
            file-name: mrbeanstorecli_1.0_amd64.deb

        - name: MacOS
          uses: ./.github/workflows/create-os-package
          with:
            os: macos-latest
            file-ext: dmg
            file-name: MrBeanStoreCLI-1.0.dmg

        - name: Windows
          uses: ./.github/workflows/create-os-package
          with:
            os: windows-latest
            file-ext: exe
            file-name: MrBeanStoreCLI-1.0.exe