name: Package Artifacts
on: 
  push:
    tags:
      - "*"

permissions:
  id-token: write
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Package-Artifacts:
    if: contains(github.ref, 'main') || contains(github.ref, 'develop')
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: pulumi-github-oidc
      
      - name: Get Release Upload URL File
        run: aws s3api get-object --bucket ${{ secrets.AWS_BUCKET_NAME }} --key upload_url upload_url

      - name: Env Upload URL
        shell: pwsh
        run: |
          $url = Get-Content -Path ".\upload_url" -TotalCount 1
          Add-Content -Path $env:GITHUB_ENV -Value "UPLOAD_URL=$url"

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Create Essential Packages
        working-directory: cli
        run: ./mvnw package
      
      - name: Create Runtime
        working-directory: cli
        run: |
          jlink --output minimal-jvm --module-path ./target/lib --add-modules java.base,java.xml,java.sql,java.prefs,java.desktop
      
      - name: Build Artifacts
        working-directory: cli
        run: |
          jpackage --type exe -n MrBeanStoreCLI --runtime-image minimal-jvm --main-jar MrBeanStoreCLI-0.0.1-SNAPSHOT.jar -i .\target\ --win-menu --win-console

      - name: Upload CLI Artifactis
        id: release_artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./cli/MrBeanStoreCLI-1.0.exe
          asset_name: MrBeanStoreCLI-1.0.exe
          asset_content_type: application/zip