name: Package Artifacts
on: 
  push:
    tags:
      - "*"
    branches:
      - feature/cli_package_action

permissions:
  id-token: write
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Package-Artifacts:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: pulumi-github-oidc

      ## TEST
      - name: Create Release Tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          tag_prefix: v


      - name: Create Release
        id: create_release
        uses: avakar/tag-and-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}

      - name: Store Release Upload URL
        run: |
          echo "${{ steps.create_release.outputs.upload_url }}" >> upload_url
          aws s3 cp ./upload_url s3://${{ secrets.AWS_BUCKET_NAME }}
      
      ## ENDTEST
      - name: Get Release Upload URL File
        run: aws s3api get-object --bucket ${{ secrets.AWS_BUCKET_NAME }} --key upload_url upload_url

      - name: Env Upload URL For Unix Systems
        run: echo "UPLOAD_URL=$(head -1 ./upload_url)" >> $GITHUB_ENV

      - name: Ubuntu
        uses: ./.github/workflows/create-os-package.yml
        with:
          os: ubuntu-latest
          file-ext: deb
          file-name: mrbeanstorecli_1.0_amd64.deb
          upload-url: ${{ env.UPLOAD_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: MacOS
        uses: ./.github/workflows/create-os-package
        with:
          os: macos-latest
          file-ext: dmg
          file-name: MrBeanStoreCLI-1.0.dmg
          upload-url: ${{ env.UPLOAD_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Windows
        uses: ./.github/workflows/create-os-package
        with:
          os: windows-latest
          file-ext: exe
          file-name: MrBeanStoreCLI-1.0.exe
          upload-url: ${{ env.UPLOAD_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
