name: Accepted Pull Request
on:
  push:
    branches:
      - feature/pulumi_*
      - main
      - develop
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
permissions:
  id-token: write
  contents: read
jobs:
  Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      
      - name: Check file system
        run: |
          "ls -al"
          "git branch"         